DROP TABLE IF EXISTS bingo_user_fields;
DROP TABLE IF EXISTS bingo_fields;
DROP TABLE IF EXISTS bingo_users;
DROP TABLE IF EXISTS bingos;
DROP TABLE IF EXISTS bingo;
DROP TABLE IF EXISTS user_tokens;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_permission;
DROP TYPE IF EXISTS bingo_field_status
